name: Selenium Tests Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allow manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Build project
        run: mvn clean package -DskipTests
      - name: Start app
        run: java -jar target/bookhive-0.0.1-SNAPSHOT.jar &
      - name: Wait for app to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app..."
            sleep 2
          done

      - name: Run Regression Tests
        run: mvn clean test -P regression
        continue-on-error: true # ✅ prevents stopping before artifacts are uploaded

      - name: Upload Extent Reports
        if: always() # ✅ runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: reports/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots/
